2 spaces!

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -6,8 +6,8 @@ $CMD
 RESULT=$?
 
 if [ $RESULT -ne 0 ]; then
-        echo "failed $CMD"
-        exit $RESULT
+  echo "failed $CMD"
+  exit $RESULT
 fi
 
 exit 0
